package com.tianque.core.systemLog.util;

public interface ModuleConstants {
	final String SEPARATOR="->";

	final String SYSTEM_MANAGE="系统管理";
	final String BASE_INFORMATION="基础数据";
    final String IMPORTANT_PERSON="重点人员";
    final String IMPORTANT_PLACE="重点场所";
    final String BIRTH_CONTROL="计生";
    final String CIVIL_ADMINISTRATION="民政";
    final String PARTY_CONSTRUCTION="党建";
    final String IMPORTANT=IMPORTANT_PLACE+SEPARATOR;
	final String USER_MANAGE=SYSTEM_MANAGE+SEPARATOR+"用户管理";
	final String ROLE_MANAGE=SYSTEM_MANAGE+SEPARATOR+"岗位管理";
	final String DEPARTMENT_MANAGE=SYSTEM_MANAGE+SEPARATOR+"部门管理";
	final String PROPERTYDICT_MANAGE=SYSTEM_MANAGE+SEPARATOR+"系统属性管理";
	final String HOUSEINFO="住房信息";
	final String ACTUAL_HOUSE="实有房屋信息";
	final String RENTAL_HOUSE="出租房信息";



	final String RESIDENT=BASE_INFORMATION+SEPARATOR+"户籍人口";
	final String TRAMP_RESIDENT=BASE_INFORMATION+SEPARATOR+"流动人口";
	final String ACTUALPOPULATION=BASE_INFORMATION+SEPARATOR+"实有人口";

	final String HOUSEHOLDSTAFF=ACTUALPOPULATION+"户籍人口";
	final String UNSETTEDPOPULATION=ACTUALPOPULATION+"未落户人口";
	final String FLOATINGPOPULATION=ACTUALPOPULATION+"流动人口";
	final String DRUGGY=IMPORTANT_PERSON+SEPARATOR+"吸毒人员";
	final String SERVICETEAMMEMBER=IMPORTANT_PERSON+SEPARATOR+"团队服务成员";
	final String SERVICETEAM="服务团队";
	final String SUPERIORVISIT=IMPORTANT_PERSON+SEPARATOR+"重点上访人员";
	final String MENTALPATIENT=IMPORTANT_PERSON+SEPARATOR+"精神病人员";
	final String POSIVITEINFO=IMPORTANT_PERSON+SEPARATOR+"刑释解教人员";
	final String RECTIFICATIVE_PERSON=IMPORTANT_PERSON+SEPARATOR+"社区矫正人员";
	final String IDLEYOUTH=IMPORTANT_PERSON+SEPARATOR+"重点青少年";
	final String AIDNEEDPOPULATION=IMPORTANT_PERSON+SEPARATOR+"需救助人员";
	final String DANGEROUSEGOODS_PRACTITIONER=IMPORTANT_PERSON+SEPARATOR+"危险品从业人员";
	final String OTHERATTENTION_PERSONNEL=IMPORTANT_PERSON+SEPARATOR+"其他人员";
	final String POORPEOPLE=IMPORTANT_PERSON+SEPARATOR+"需要救助人员";
	final String OVERSEAPEOPLE=IMPORTANT_PERSON+SEPARATOR+"境外人员";

	final String DANGEROUSCHEMICALSUNIT=IMPORTANT_PLACE+SEPARATOR+"危险化学品单位";
	
	
	final String LETTING_HOUSE=IMPORTANT_PLACE+SEPARATOR+"出租房";
	final String ENTERPRISE=IMPORTANT_PLACE+SEPARATOR+"规上企业";
	final String SCHOOL=IMPORTANT_PLACE+SEPARATOR+"学校";
	final String HOSPITAL=IMPORTANT_PLACE+SEPARATOR+"医院";
	final String COMPLEX_PLACE=IMPORTANT_PLACE+SEPARATOR+"公共复杂场所";
	final String SPECIALTRADE=IMPORTANT_PLACE+SEPARATOR+"特种行业";
	final String NEWSOCIETY_FEDERATION=IMPORTANT_PLACE+SEPARATOR+"社会组织";
	final String SAFE_PLACE=IMPORTANT_PLACE+SEPARATOR+"安全生产重点";
	final String FIRESAFETYKEY=IMPORTANT_PLACE+SEPARATOR+"消防安全重点";
	final String SECURITYKEY=IMPORTANT_PLACE+SEPARATOR+"治安重点";
	final String OTHER_LOCATION=IMPORTANT_PLACE+SEPARATOR+"其他场所";
	final String CONSTRUCTION_UNIT=IMPORTANT_PLACE+SEPARATOR+"建筑施工单位";
	final String HANDICAPPED=BASE_INFORMATION+SEPARATOR+"残疾人";
	final String ELDERLYPEOPLE=BASE_INFORMATION+SEPARATOR+"老年人";
	final String NURTURESWOMEN=BIRTH_CONTROL+SEPARATOR+"育妇";


	final String OPTIMALOBJECT=CIVIL_ADMINISTRATION+SEPARATOR+"优抚对象";
	final String PARTYMEMBERINFO=PARTY_CONSTRUCTION+SEPARATOR+"本级党建党员信息";
	final String PARTYORGACTIVITY=PARTY_CONSTRUCTION+SEPARATOR+"本级党建党组织活动记录";
	final String LOWERPARTORGINFO=PARTY_CONSTRUCTION+SEPARATOR+"下级党建党组织信息";

	final String PUBLICPLACE =IMPORTANT_PLACE+SEPARATOR+"公共场所";

	final String SERVICE_RECORD = "监管记录";


}
